#goal definition
int32 wall_id
PointArray wall_points
---
#result definition
bool success
---
#feedback definition
string phase        # e.g. "NAVIGATING_TO_WALL", "FOLLOWING_WALL", "RETURNING", "COMPLETED"
#geometry_msgs/Point current_position